// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhA_NYn5Pmwq_2T0z2HrDP3xCCCPlXHOY',
    appId: '1:795137276652:android:03979e64b8a2eb8f42c3c9',
    messagingSenderId: '795137276652',
    projectId: 'balaghak-c28d2',
    storageBucket: 'balaghak-c28d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn_1KTdZ_gF2DUszgqutxdUtKtqtGbl6Q',
    appId: '1:795137276652:ios:311355bbd192596242c3c9',
    messagingSenderId: '795137276652',
    projectId: 'balaghak-c28d2',
    storageBucket: 'balaghak-c28d2.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTd0q8Xy2t5_BDEAV56tOyEpG1hA2z29Q',
    appId: '1:795137276652:web:d3bc2d4773b070bf42c3c9',
    messagingSenderId: '795137276652',
    projectId: 'balaghak-c28d2',
    authDomain: 'balaghak-c28d2.firebaseapp.com',
    storageBucket: 'balaghak-c28d2.firebasestorage.app',
    measurementId: 'G-M5D6EXDB2W',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTd0q8Xy2t5_BDEAV56tOyEpG1hA2z29Q',
    appId: '1:795137276652:web:0c8df28103ee128142c3c9',
    messagingSenderId: '795137276652',
    projectId: 'balaghak-c28d2',
    authDomain: 'balaghak-c28d2.firebaseapp.com',
    storageBucket: 'balaghak-c28d2.firebasestorage.app',
    measurementId: 'G-66KBQW5XBF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn_1KTdZ_gF2DUszgqutxdUtKtqtGbl6Q',
    appId: '1:795137276652:ios:311355bbd192596242c3c9',
    messagingSenderId: '795137276652',
    projectId: 'balaghak-c28d2',
    storageBucket: 'balaghak-c28d2.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

}